<?php

namespace AppBundle\Repository;

/**
 * AdminsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminsRepository extends \Doctrine\ORM\EntityRepository
{
}
