<?php

namespace AppBundle\Repository;

/**
 * CoacheStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoacheStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
