<?php

namespace AppBundle\Repository;

/**
 * CoachesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoachesRepository extends \Doctrine\ORM\EntityRepository
{
}
