<?php

namespace AppBundle\Repository;

/**
 * CoachesPositionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoachesPositionsRepository extends \Doctrine\ORM\EntityRepository
{
}
