<?php

namespace AppBundle\Repository;

/**
 * PlayerToPlayerRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerToPlayerRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
