<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Players;
use AppBundle\Entity\Teams;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;

/**
 * PlayersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayersRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em,new \Doctrine\ORM\Mapping\ClassMetadata(Players::class));
    }


    public function getPlayerTeam(Players $player){
        if ($player->getYouthTeams() != null){
            $team = $player->getYouthTeams();
        }else{
            $team = $player->getTeam();
        }
        return $team;
    }



}
