<?php

namespace AppBundle\Repository;

/**
 * PlayerTeamRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerTeamRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
