<?php

namespace AppBundle\Repository;

/**
 * PlayersInjuredRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayersInjuredRepository extends \Doctrine\ORM\EntityRepository
{
}
