<?php

namespace AppBundle\Repository;

/**
 * PlayerToTeamRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerToTeamRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
