<?php

namespace AppBundle\Repository;

/**
 * TeamToPlayerRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamToPlayerRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
