<?php

namespace AppBundle\Repository;

/**
 * TeamPlayerRegisterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamPlayerRegisterRepository extends \Doctrine\ORM\EntityRepository
{
}
