<?php

namespace AppBundle\Repository;

/**
 * TeamCoacheRegisterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamCoacheRegisterRepository extends \Doctrine\ORM\EntityRepository
{
}
