<?php

namespace AppBundle\Repository;

/**
 * TeamCupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamCupsRepository extends \Doctrine\ORM\EntityRepository
{
}
