<?php

namespace AppBundle\Repository;

/**
 * UsersCupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersCupsRepository extends \Doctrine\ORM\EntityRepository
{
}
