<?php

namespace AppBundle\Repository;

/**
 * YouthTeamPlayerRegisterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YouthTeamPlayerRegisterRepository extends \Doctrine\ORM\EntityRepository
{
}
