<?php

namespace AppBundle\Repository;

/**
 * YouthTeamCoacheRegisterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YouthTeamCoacheRegisterRepository extends \Doctrine\ORM\EntityRepository
{
}
