<?php

namespace AppBundle\Repository;

/**
 * YouthTeamCupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YouthTeamCupsRepository extends \Doctrine\ORM\EntityRepository
{
}
