<?php

namespace AppBundle\Repository;

/**
 * YouthTeamsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YouthTeamsRepository extends \Doctrine\ORM\EntityRepository
{
}
