<?php

namespace AppBundle\Repository;

/**
 * YouthDivisionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YouthDivisionsRepository extends \Doctrine\ORM\EntityRepository
{
}
