<?php

namespace AppBundle\Repository\PlayerProperties;

/**
 * CupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CupsRepository extends \Doctrine\ORM\EntityRepository
{
}
