<?php

namespace AppBundle\Repository\PlayerProperties;

/**
 * FoodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FoodRepository extends \Doctrine\ORM\EntityRepository
{
}
