<?php

namespace AppBundle\Repository\PlayerProperties;

/**
 * PlayerStatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerStatsRepository extends \Doctrine\ORM\EntityRepository
{
}
