<?php

namespace AppBundle\Repository\PlayerProperties;

/**
 * PositionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PositionsRepository extends \Doctrine\ORM\EntityRepository
{
}
