<?php

namespace AppBundle\Repository\PlayerProperties;

/**
 * WaterGlassesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WaterGlassesRepository extends \Doctrine\ORM\EntityRepository
{
}
